import { PropsWithChildren } from 'react'

import type { Metadata } from 'next'

import './globals.css'
import { Providers } from './providers'
import '@lobstr/react/dist/output.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className="w-full items-center flex flex-col bg-white">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
